version: '3.8'
services:
  app:
    build: .
    container_name: project_app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
    volumes:
      - .:/app
    ports:
      - "8000:8000"
